config/routes.rb
Videoapp::Application.routes.draw do
  resources :chapter_elements

  resources :chapters

  resources :courses

  get '/uploads', to: 'uploads#index'
  post '/uploads', to: 'uploads#post_video_to_wistia'

  root "pages#home"

  

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :course
end

app/models/chapter_element.rb
class ChapterElement < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :chapters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapter_elements_controller.rb
class ChapterElementsController < ApplicationController
  before_action :set_chapter_element, only: [:show, :edit, :update, :destroy]

  # GET /chapter_elements
  # GET /chapter_elements.json
  def index
    @chapter_elements = ChapterElement.all
  end

  # GET /chapter_elements/1
  # GET /chapter_elements/1.json
  def show
  end

  # GET /chapter_elements/new
  def new
    @chapter_element = ChapterElement.new
  end

  # GET /chapter_elements/1/edit
  def edit
  end

  # POST /chapter_elements
  # POST /chapter_elements.json
  def create
    @chapter_element = ChapterElement.new(chapter_element_params)

    respond_to do |format|
      if @chapter_element.save
        format.html { redirect_to @chapter_element, notice: 'Chapter element was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chapter_element }
      else
        format.html { render action: 'new' }
        format.json { render json: @chapter_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter_elements/1
  # PATCH/PUT /chapter_elements/1.json
  def update
    respond_to do |format|
      if @chapter_element.update(chapter_element_params)
        format.html { redirect_to @chapter_element, notice: 'Chapter element was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chapter_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapter_elements/1
  # DELETE /chapter_elements/1.json
  def destroy
    @chapter_element.destroy
    respond_to do |format|
      format.html { redirect_to chapter_elements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter_element
      @chapter_element = ChapterElement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_element_params
      params.require(:chapter_element).permit(:title, :description, :position)
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chapter }
      else
        format.html { render action: 'new' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :description, :position)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def home
  end

  def uploadFile
  end

  require 'net/http'
  require 'net/http/post/multipart'

  def post_video_to_wistia(picture, datafile)
  	uri = URI('https://upload.wistia.com/')

  	http = Net::HTTP.new(uri.host, uri.port)
  	http.use_ssl = true

  	# Construct the request.
  	request = Net::HTTP::Post::Multipart.new uri.request_uri, {
    'api_password' => '<API_PASSWORD>',
    'contact_id'   => '<CONTACT_ID>', # Optional.
    'project_id'   => '<PROJECT_ID>', # Optional.
    'picture'      => '<MEDIA_NAME>', # Optional.

    'file' => UploadIO.new(
                File.open(datafile),
                'application/octet-stream',
                File.basename(datafile)
              )
  	}

  # Make it so!
  response = http.request(request)

  return response
end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapter_elements_helper.rb
module ChapterElementsHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chapter_elements/_form.html.erb
<%= form_for(@chapter_element) do |f| %>
  <% if @chapter_element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter_element.errors.count, "error") %> prohibited this chapter_element from being saved:</h2>

      <ul>
      <% @chapter_element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapter_elements/edit.html.erb
<h1>Editing chapter_element</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter_element %> |
<%= link_to 'Back', chapter_elements_path %>

app/views/chapter_elements/index.html.erb
<h1>Listing chapter_elements</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Position</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chapter_elements.each do |chapter_element| %>
      <tr>
        <td><%= chapter_element.title %></td>
        <td><%= chapter_element.description %></td>
        <td><%= chapter_element.position %></td>
        <td><%= link_to 'Show', chapter_element %></td>
        <td><%= link_to 'Edit', edit_chapter_element_path(chapter_element) %></td>
        <td><%= link_to 'Destroy', chapter_element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter element', new_chapter_element_path %>

app/views/chapter_elements/new.html.erb
<h1>New chapter_element</h1>

<%= render 'form' %>

<%= link_to 'Back', chapter_elements_path %>

app/views/chapter_elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chapter_element.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @chapter_element.description %>
</p>

<p>
  <strong>Position:</strong>
  <%= @chapter_element.position %>
</p>

<%= link_to 'Edit', edit_chapter_element_path(@chapter_element) %> |
<%= link_to 'Back', chapter_elements_path %>

app/views/chapters/_form.html.erb
<%= form_for(@chapter) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<h1>Listing chapters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Position</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.title %></td>
        <td><%= chapter.description %></td>
        <td><%= chapter.position %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chapter.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @chapter.description %>
</p>

<p>
  <strong>Position:</strong>
  <%= @chapter.position %>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Videoapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/uploads/index.html.erb
<h1>File Upload</h1>


<%= form_tag('/uploads', action: "post_video_to_wistia", method: :post, multipart: true) do %>
 
<%= file_field 'picture', 'datafile' %></p>
<%= submit_tag "Upload" %>
<% end %>

app/views/uploads/index22.html.erb
<h1>File Upload</h1>


<%= form_tag({action: :post_video_to_wistia(picture, datafile)}, multipart: true) do %>
 
<%= file_field 'picture', 'datafile' %></p>
<%= submit_tag "Upload" %>
<% end %>